### ISSUE TITLE
mportError: cannot import name 'route' from partially initialized module 'tmdb'

### ISSUE THREAD

**Issue by DCMarine** [leandcesar/themoviedb#1]
Using any of your base samples to get this working fails with "cannot import name 'xxxxxx'"

Error:
Traceback (most recent call last):
  File "/Volumes/OneDrive/Python/rss/tmdb.py", line 2, in <module>
    from tmdb import route
  File "/Volumes/OneDrive/Python/rss/tmdb.py", line 2, in <module>
    from tmdb import route
ImportError: cannot import name 'route' from partially initialized module 'tmdb' (most likely due to a circular import) (/Volumes/OneDrive/Python/rss/tmdb.py)

**Comment by leandcesar** [comment]
The library was rewritten, fixing several errors: [themoviedb](https://pypi.org/project/themoviedb/)
